### ISSUE TITLE
Unable To detect other Diseases rather than LateBlight

### ISSUE THREAD

**Issue by mady143** [2052sagar/PlantDiseaseDetection#3]
Hello @2052sagar,

I had successfully run the project at first i had run the **cnn.py** and generated the model and finish the training also later in run **ui.py** and tested the few images but i am getting the same disease name **lateblight** for every Image 
can you clarify me whether i am doing right or wrong and please help me in this 

Thanks & Regards,
Manikantha.

Happy cooding....

**Comment by 2052sagar** [comment]
This isn't due to the error in the code. It might be the case that you
every time choose same image type for testing. Or while you test the first
image and tried to test the second image then there might be a case where
first image is not being replaced by the second image so that the same
result has occurred for every time. please check for this two condition.
this might solve your problem.

**Comment by mmusunur** [comment]
Thank you @2052sagar ,

from **Test** folder only i can do the test the image to get the result or else any other folder actually i was tested through downloading an image from the google so thats the reason i am getting the same  disease name could you help in this 

Thanks & Regards,
Manikantha.

Happy Codding......

**Comment by 2052sagar** [comment]
the project which is in the github is just for proto type and the data i
used for training was just few sets of images. But in actual we need many
dataset. I think the problem arises due to this reason. The images you
downloaded mightn't be of tomato and it might not be of 3 diseases that is
in tomato or healthy leaf og tomato. Are you clear that the data set I used
is only of few sample ? due to this it cant detect wide range of plant
leaf. This might be the problem with you.

**Comment by mmusunur** [comment]
Thank you @2052sagar 
Its very helpfull and if any queries regarding this i will contact you

Thanks & Regards,
Manikantha.

Happy Codding...
